### ISSUE TITLE
Cambiar estrategia de herencia

### ISSUE THREAD

**Issue by cbiale** [ulisescolina/UC-POOI#6]
En Tecnico cambiar:
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS) en Tecnico

Usar otra estrategia, como por ejemplo:
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "tipo_empleado")

**Comment by crulises** [comment]
Cuestión solucionada en el commit 043adbd
